### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by TarunavBA** [bionic-py/Bionic#21]
1. I would like a new branch named `Tests` for commiting and pushing **non-production** ready commits. 
2. Would also like instructions for installing bionic from that Tests branch. (For latest bleeding edge version of Bionic)
3. Finally I would like you to add the `hacktoberfest` and `WIP` labels to attract contributors. 😜

**Comment by shajin-sha** [comment]
sure as your wish😀

**Comment by TarunavBA** [comment]
Thankssssss 🤗
