### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by TarunavBA** [bionic-py/Bionic#8]
Hey @shajin-sha please create a new account in codestream and install the plugin in vscode and make a new team and invite me to it. So we both can collaborate and make bionic een better.

**Comment by shajin-sha** [comment]
> Hey @shajin-sha please create a new account in codestream and install the plugin in vscode and make a new team and invite me to it. So we both can collaborate and make bionic een better. 

For sure.

**Comment by TarunavBA** [comment]
Thanks! @shajin-sha

~ 🤖
